name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (Ruff)
        run: ruff check --output-format=github

      - name: Format check (Black)
        run: black --check --line-length 100 --target-version py313 src tests

      - name: Run tests
        run: pytest -q --cov=src/portfolio_advisor --cov-report=xml --cov-report=term-missing

      - name: Enforce coverage >= 80%
        run: |
          python - <<'PY'
          import sys, xml.etree.ElementTree as ET
          tree = ET.parse('coverage.xml')
          cov = float(tree.getroot().attrib['line-rate'])*100
          print(f"Total coverage: {cov:.2f}%")
          sys.exit(0 if cov >= 80 else 1)
          PY


